### ISSUE TITLE
There is an issue where that noise becomes nan.

### ISSUE THREAD

**Issue by carpediem190603** [theoad/dot-dmax#3]
```
def gaussian_transport_operators(cov_source: Tensor, cov_target: Tensor, eps: float = 1e-5) -> Tuple[Tensor, Optional[Tensor]]:

    I = eye_like(cov_source)

    if is_spd(cov_source, strict=True, eps=eps).all():
        sqrtCs, isqrtCs = sqrtm(cov_source), invsqrtm(cov_source)
        T0 = isqrtCs @ sqrtm(make_psd(sqrtCs @ cov_target @ sqrtCs, strict=True, eps=eps)) @ isqrtCs
        Cw0 = None
    else:
        sqrtCt, isqrtCt = sqrtm(cov_target), invsqrtm(make_psd(cov_target, strict=True, eps=eps))
        mix = sqrtm(make_psd(sqrtCt @ cov_source @ sqrtCt, strict=False, eps=eps))
        T_star = isqrtCt @ mix @ isqrtCt
        pinvCs = torch.linalg.pinv(cov_source, atol=eps ** 0.5)
        T0 = (sqrtCt @ mix @ isqrtCt @ pinvCs)
        Cw0 = sqrtCt @ (I - sqrtCt @ T_star @ pinvCs @ T_star @ sqrtCt) @ sqrtCt

    assert T0.shape == cov_source.shape
    return T0, Cw0

def transport(features: Tensor, mean_source: Tensor, mean_target: Tensor, T0: Tensor, Cw0: Optional[Tensor], pg_star: float = 0.) -> Tensor:

    T = (1 - pg_star) * T0 + pg_star * eye_like(T0)
    features_centered = (features - mean_source[..., None, :])
    transported = (T @ features_centered[..., None]).squeeze() + mean_target[..., None, :]
    if Cw0 is not None and pg_star != 1:
        noise = MultivariateNormal(torch.zeros_like(mean_target), Cw0 * (1 - pg_star) ** 0.5)
        transported += noise.sample()[..., None, :]
    return transported
```

If `is_spd(cov_source, strict=True, eps=eps).all()` is the case, then `noise` is not necessary. Otherwise, if it is not the case, then `noise` needs to be obtained, but there is an issue where that `noise` becomes `nan`.

**Comment by theoad** [comment]
Hi,
Yes this can happen if the matrix in the denominator (the one for which we compute the pseudo-inverse) is ill-conditioned.
You can try to use a bigger stabilizer value for ‘eps’, but this ultimately depends on your data.

**Comment by carpediem190603** [comment]
I've tried modifying the `eps`, but it hasn't been resolved. It doesn't seem to be an issue with the `eps`.

**Comment by theoad** [comment]
Are cov_source and cov_target valid (do they contain NaN or Inf values) ? What is the first matrix that becomes NaN ?
Did you manage to reproduce the results with the datasets of the paper, or is there a problem there too ?

**Comment by carpediem190603** [comment]
cov_source and cov_target do not contain NaN and Inf. NaN first occurs in `noise.sample()`. I am using a dataset different from the one in the paper. In train, the images are being used in batch size.

**Comment by theoad** [comment]
Can you tell which component of the noise matrix is NaN ? isqrtCt, mix, T_star, pinv ?

**Comment by carpediem190603** [comment]
NaN occurs when passing through MultivariateNormal().

**Comment by theoad** [comment]
Yes. This is because the covariance matrix has NaN hence torch is not happy. But we knew that already. What I’m trying to figure out is which part of the covariance formula is NaN:
isqrtCt, mix, T_star or pinv ?

**Comment by carpediem190603** [comment]
None of them contain NaN. Cw0 is also not NaN.

**Comment by carpediem190603** [comment]
I solved it.

**Comment by theoad** [comment]
Great. Feel free to share your solution here for others to enjoy your fix :)
